const TICKET_STATUS=["ACTIVE","BOOKED","SCANNED","EXPIRED"]
const TICKET_STATUS_OBJ={ACTIVE:"ACTIVE",BOOKED:"BOOKED",SCANNED:"SCANNED",EXPIRED:"EXPIRED"}
const TICKET_CATEGORY=["GENERAL","VIP","VVIP"]
const TICKET_CATEGORY_OBJ={GENERAL:"GENERAL",VIP:"VIP",VVIP:"VVIP"}
const USER_TYPE=["USER",'ADMIN',"ORGANIZER"]
const USER_TYPE_OBJ={USER:"USER",ADMIN:'ADMIN',ORGANIZER:"ORGANIZER"}
const USER_STATUS=["ACTIVE","INACTIVE","BLOCKED"]
const USER_STATUS_OBJ={ACTIVE:"ACTIVE",INACTIVE:"INACTIVE",BLOCKED:"BLOCKED"}


const ROLE_NAME=["USER","ORGANIZER","ADMIN"]
module.exports={
    USER_TYPE,
    TICKET_CATEGORY,
    TICKET_STATUS,
    USER_STATUS,
    ROLE_NAME,
    USER_STATUS_OBJ,
    USER_TYPE_OBJ,
    TICKET_CATEGORY_OBJ,
    TICKET_STATUS_OBJ
}